apiVersion: v1
kind: Namespace
metadata:
  name: guestbookxxx
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---    
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbookxxx
spec:
  generators:
  - list:
      elements:
      - cluster: local
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{cluster}}-guestbookxxx'
    spec:
      project: default
      source:
        repoURL: https://github.com/jmespinosa-phi/argocd-example-apps.git
        targetRevision: HEAD
        path: guestbook
      destination:
        server: '{{url}}'
        namespace: guestbookxxx